### PR TITLE
Add npm version build scripts

### PR DESCRIPTION
**Pull request by doktordirk**
usage eg:
`npm version patch && npm publish`

npm (pre)version: (tags and does a git commit afterwards itself)
- lint
- test
- build
- bump
- ensure package consistency
- git add changes

npm postpublish:
- push to git
- push tag to git

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk works nice. will get better with a small update once jspm postinstall scripts are available

**Comment by RWOverdijk** [comment]
@doktordirk Did you test this somewhere?

**Comment by doktordirk** [comment]
you can run the `npm version patch` savely on a fork branch (need to delete the local tag later though)

ps: should i rebase? this was on top of the orther PRs

**Comment by doktordirk** [comment]
i.ll move parts to prepublish. that.ll make it clearer

**Comment by doktordirk** [comment]
moved:
some question remain:
prepublish vs postpublish? (solved: prepublish doesn't work as it runs on npm install)
lint & test needed ?

**Comment by doktordirk** [comment]
why is the test running prepublish?

**Comment by doktordirk** [comment]
rebased for clarity

**Comment by RWOverdijk** [comment]
prepublish doesn't seem to be a problem anymore. 👍

**Comment by RWOverdijk** [comment]
Also, could you test it before we merge this?

**Review by RWOverdijk — APPROVED** [review]

**Comment by doktordirk** [comment]
@RWOverdijk there was indeed a problem. fixed now. you can then test it with `npm version patch` as that's completely save. the git committing is still at postpublish

ps: why is there no review required after additional commits??

**Comment by RWOverdijk** [comment]
@doktordirk I don't know. And ok. 👍

**Pull request merged**
