### PR TITLE
Value converter

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Could you add a description to explain the PR? I've tried to gather it from the code but it's a lot to take in.

**Comment by doktordirk** [comment]
new is only https://github.com/SpoonX/aurelia-authentication/pull/110/commits/bfa75c6628a9b7438f8b81de107e8534c98c90eb
and https://github.com/SpoonX/aurelia-authentication/pull/110/commits/113df8b9d439becb161f6220346641e45d2c8631
which have descriptions and dont have much changes to look at. the other stuff comes from unmerged/still_not_thump_uped older PRS

**Comment by doktordirk** [comment]
rebased to make it easier

**Comment by RWOverdijk** [comment]
Looks a lot better, thanks :) I dig this PR 👍

**Comment by doktordirk** [comment]
i might re-work parts

**Pull request closed without merging**
