### PR TITLE
Fix authFilter bundle

### LINKED ISSUE #44: App breaks when bundled (missing authFilter import)
My bundle is missing authFilter:

``` js
...
      "github:polymer/mutationobservers@0.4.2/MutationObserver.js",
      "github:spoonx/aurelia-api@2.0.7.js",
      "github:spoonx/aurelia-api@2.0.7/config.js",
      "github:spoonx/aurelia-api@2.0.7/endpoint.js",
      "github:spoonx/aurelia-api@2.0.7/index.js",
      "github:spoonx/aurelia-api@2.0.7/rest.js",
      "github:spoonx/aurelia-auth@0.13.6.js",
      "github:spoonx/aurelia-auth@0.13.6/app.fetch-httpClient.config.js",
      "github:spoonx/aurelia-auth@0.13.6/authService.js",
      "github:spoonx/aurelia-auth@0.13.6/authUtils.js",
      "github:spoonx/aurelia-auth@0.13.6/authentication.js",
      "github:spoonx/aurelia-auth@0.13.6/authorizeStep.js",
      "github:spoonx/aurelia-auth@0.13.6/baseConfig.js",
      "github:spoonx/aurelia-auth@0.13.6/index.js",
      "github:spoonx/aurelia-auth@0.13.6/oAuth1.js",
      "github:spoonx/aurelia-auth@0.13.6/oAuth2.js",
      "github:spoonx/aurelia-auth@0.13.6/popup.js",
      "github:spoonx/aurelia-auth@0.13.6/storage.js",
      "npm:aurelia-animator-css@1.0.0-beta.1.1.1.js",
...
```

authFilter is required here: https://github.com/SpoonX/aurelia-auth/blob/e62c9eb9d39d674cc218ea390fa87600b7346c9f/src/index.js#L16

But is not imported, thus not bundled and so results in a 404.

I assume you just need to add `import './authFilter';` to fix this.

### PR DESCRIPTION
**Pull request by AdamWillden**
Fixes #44

### CODE REVIEW

**Comment by AdamWillden** [comment]
ah crap why do I have a semi-colon in the commit message!

**Comment by doktordirk** [comment]
can you change that semicolon?
see  eg http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git

**Comment by AdamWillden** [comment]
Yeah I will just haven't had chance (busy weekend)!

**Comment by AdamWillden** [comment]
Done @doktordirk!

**Comment by RWOverdijk** [comment]
:+1:

**Pull request merged**
