### PR TITLE
fix(auth0): extend responseType check

### LINKED ISSUE #403: auth0-lock v11 and responseType = 'token'
I'm having the most difficult time getting the authorization flow working with Auth0.

I tried first the examples provided by the Auth0 site to integrate the authentication with my SPA, which works fine, but when I use aurelia-authentication plugin using the same config, it fails. 
The flow stops at the `/authorize` endpoint
If I set the `responseType = 'token'`, I get the following error in the console:
`Unhandled rejection TypeError: Cannot read property 'token' of null`
Other attempts:
`responseType = 'token id_token'` gives me this error:
`Unhandled rejection Error: Only 'token' responseType is supported`

`responseType = 'token%20id_token'` results in `/authroize` to return HTTP 501

If I change the line https://github.com/SpoonX/aurelia-authentication/blob/9ae76ac2a5fb6111c5ee5427587e746112911dc5/src/authLock.js#L63-L64 to
`opts.auth.responseType = provider.responseType.replace('%20', ' ');`
It seems to work. `/authorize` then returns HTTP 200

Should the following if-statement here also include to check responseType === 'token id_token'?  
https://github.com/SpoonX/aurelia-authentication/blob/9ae76ac2a5fb6111c5ee5427587e746112911dc5/src/authLock.js#L93-L96
Or am I missing something here?

I found this https://github.com/auth0/lock/issues/809, indicating responseType = 'token id_token' is now mandatory?

AuthConfig:
```js
export default {
  endpoint: 'api',
  configureEndpoints: ['api'], 
  storageKey: 'aurelia_authentication_auth0',
  providers: {
    auth0: {
      
      oauthType: 'auth0-lock',
      responseType: 'token',
      clientId: 'random',
      clientDomain: 'mydomain.eu.auth0.com',
      lockOptions: {
        auth: {          
          audience: 'http://mydomain.com/api',
          params: { scope: 'openid profile' },
        }
      },
      state: function () {
        return Math.random().toString(36).substr(2);
      }
    }
  }
};
```

### PR DESCRIPTION
**Pull request by vidaritos**
It was necessary to extend the if-check with an additional variant of responseType === 'token id_token' to make it work with auth0-lock v11

Fixes #403

### CODE REVIEW

**Comment by RWOverdijk** [comment]
That's just amazing. Thank you.

**Comment by vidaritos** [comment]
The CI build breaks what seems to be missing credentials for JSPM to use for downloading packages from GitHub. Or can it be solved using `whatwg-fetch` from the npm registry?

**Comment by RWOverdijk** [comment]
@vidaritos Yeah, when switching jobs I accidentally removed the wrong token and I haven't updated it on the plugins yet. I really should, but there's always something coming up.

**Review by RWOverdijk — APPROVED** [review]

**Comment by RWOverdijk** [comment]
Sorry for that. I've updated the token, cheers!

**Pull request merged**
