### PR TITLE
Encode uri component all query parameters

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
If I understand correctly, this will encode the entire thing in stead of just the base? Would it be difficult for you to add a small test?

**Comment by doktordirk** [comment]
what should i test for?

**Comment by RWOverdijk** [comment]
If we get the url we expect. If I'm not mistaken, this is the fourth iteration on this specific piece of code.

**Comment by doktordirk** [comment]
closed till i test oauth1

**Comment by doktordirk** [comment]
all fine

**Comment by RWOverdijk** [comment]
👍

**Comment by doktordirk** [comment]
but you are right about the test. i'll add it tomorrow

**Comment by doktordirk** [comment]
ps: oauth1 had that test already. stupid me

**Pull request merged**
