### PR TITLE
Update config options for SPA route & add nice comments

### PR DESCRIPTION
**Pull request by AdamWillden**
sorry it took so long

### CODE REVIEW

**Comment by doktordirk** [comment]
i've been testing those spa routes again. as it turns out :
- all redirect routes need to start with #/ as those pass through the server
- the login route is an internal aurelia route it starts with /. it is used to direct unlogged users to and also to prevent access to by logged in users

**Comment by AdamWillden** [comment]
I was wondering why the difference... 

How is it that the redirect ones pass through the server? Are some set via location.href and some using the router. **just looked and yes that's why**. Be nice to standardise that, unless there's good reason

**Comment by doktordirk** [comment]
i doubt there is a good reason. most code is inherited and might have some oddities. so, i agree that using aurelia Redirect everywhere would be better. so, feel free .. :-)

**Comment by AdamWillden** [comment]
@doktordirk - With respect to this PR do you want me to do anything for the moment?

**Comment by AdamWillden** [comment]
Are you asking me to do this?

``` js
// SPA related options

  // The SPA url to which the user is redirected after a successful login
  loginRedirect: '#/customer',
  // The SPA url to which the user is redirected after a successful logout
  logoutRedirect: '#/',
  // The SPA route used when an unauthenticated user tries to access an SPA page that requires authentication
  loginRoute: '/login',
  // Whether or not an authentication token is provided in the response to a successful signup
  loginOnSignup: true,
  // If loginOnSignup == false: The SPA url to which the user is redirected after a successful signup (else loginRedirect is used)
  signupRedirect: '#/login',
```

If so, do I need to update these defaults too: https://github.com/SpoonX/aurelia-auth/blob/58e9fa6d4753d28a656fc3e093d3e3205bb05159/src/baseConfig.js

**Comment by doktordirk** [comment]
@AdamWillden  yes. 
or, as you said, better even change all to Redirect. 
though maybe, one step at a time. do as you said above, we merge it, and then we'll look at that Redirect afterwards

**Comment by RWOverdijk** [comment]
I like this. The indentation seems a bit weird though, or is that just me?

**Comment by doktordirk** [comment]
i'm not a big fan of it either actually. seems you are outvoted @AdamWillden :)
maybe use something else to highlight headings

**Comment by AdamWillden** [comment]
Yeah was just to highlight headings as you said. How about:

\ I'm a heading
\ ===========

**Comment by doktordirk** [comment]
that could work. and then //------- for second level i guess

**Comment by AdamWillden** [comment]
@RWOverdijk @doktordirk how's that?

Do you want me to update the `baseConfig.js` SPA redirect defaults as part of this PR in a new commit? 

Secondly do you want that baseConfig to be reordered and contain all these comments like the readme?

**Comment by doktordirk** [comment]
@AdamWillden yeah, i'd say lets do that

**Comment by AdamWillden** [comment]
Sorted. Note commit comment:

> I ensured that no options changed during this process except for removing `signupRoute` which is not used by the application.

**Comment by AdamWillden** [comment]
Oops of course with the additional exception of the SPA routes. Are we sure they work okay with `#/`?

**Comment by AdamWillden** [comment]
Ah yes just checked my application which contains this:

``` js
    // The SPA url to which the user is redirected after a successful login
    loginRedirect: '#',
    // The SPA url to which the user is redirected after a successful logout
    logoutRedirect: '#login',
    // The SPA route used when an unauthenticated user tries to access an SPA page that requires authentication
    loginRoute: 'login',
    // Whether or not an authentication token is provided in the response to a successful signup
    loginOnSignup: true,
    // If loginOnSignup == false: The SPA url to which the user is redirected after a successful signup (else loginRedirect is used)
    signupRedirect: '#login',
```

**Comment by doktordirk** [comment]
yep. i tested all combinations :) . /#login works too, but above is the clearest i think

**Comment by doktordirk** [comment]
yours also fine i guess.

**Comment by AdamWillden** [comment]
Ah crap - I guess some tests use the old values...

My bad I'll get it fixed.

**Comment by AdamWillden** [comment]
Rebased commits and changed commit order to make sense. Still not sure if I should classify the last commit as refactor or doc as it's commenting the code and updating the readme.

Please review. I think we're there now.

**Comment by doktordirk** [comment]
well, again, keep it coming _smile_

**Pull request merged**
