### PR TITLE
Build 3.0.0-rc11

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk please review, merge and npm

**Comment by AdamWillden** [comment]
@RWOverdijk @doktordirk any chance we can get this published early this morning? We're doing a client release today and I'd love to get the #253 PR into our release.

Believe me I do appreciate that you already do release so often! Thought it wouldn't hurt to ask :-)

**Review by RWOverdijk — APPROVED** [review]

**Comment by RWOverdijk** [comment]
@AdamWillden Done.

**Comment by AdamWillden** [comment]
@RWOverdijk thank you!

**Pull request merged**
