### PR TITLE
Add a configuration option for the refresh token requests

### PR DESCRIPTION
**Pull request by cb-fred**
This pull requests adds a `refreshTokenSubmitProp` that can be used to change the name of the prop used to send the token for token refresh.

### CODE REVIEW

**Review by doktordirk — CHANGES_REQUESTED** [review]
can you kick the dist folder changes? we do that when there's a new release.  for PRs they just clutter

**Comment by cb-fred** [comment]
done

**Review by doktordirk — APPROVED** [review]

**Comment by cb-fred** [comment]
Hi, any idea on the release schedule ? Is this feature planned for the next RC ?

**Comment by doktordirk** [comment]
i'ts merged, so yes. and should get out this week

**Comment by cb-fred** [comment]
Ok perfect !

**Pull request merged**
