### PR TITLE
feat(BaseConfig): copied over current sahat/satellizer settings

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by doktordirk** [comment]
@msalman86 i copied over the current settings from sahat/satellizer . they should work for linkedin as well without extra encoding. can you test if those work for you

**Comment by RWOverdijk** [comment]
👍

**Comment by doktordirk** [comment]
i'll double check and then merge

**Comment by 0xSalman** [comment]
@doktordirk I apologize for not being able to respond earlier. I have verified that the linkedin is working with new changes without extra encoding. 👍

**Comment by RWOverdijk** [comment]
👍  :)

**Pull request merged**
