### PR TITLE
feat(authService): optional callback for isAuthenticated

### PR DESCRIPTION
**Pull request by doktordirk**
ref https://github.com/SpoonX/aurelia-authentication/issues/288

### CODE REVIEW

**Comment by doktordirk** [comment]
@bas080 @VMBindraban 

@nexbit i left the status refreshing out for now. would have to make sure it's on all the right places

**Review by VMBindraban — APPROVED** [review]

**Review by bas080 — APPROVED** [review]

**Comment by VMBindraban** [comment]
@RWOverdijk Review please.

**Comment by RWOverdijk** [comment]
@doktordirk Why isn't this a promise instead? Either way I can live with the solution provided 👍

**Review by RWOverdijk — APPROVED** [review]

**Comment by doktordirk** [comment]
@RWOverdijk you.ve a bad memory. i.ve made it a promise once (per option) and you rejected it. anyways, to be BC

**Comment by RWOverdijk** [comment]
@doktordirk I don't have bad memory, I have tons of stuff flying by daily. I can't keep track of every tiny thing.

But good argument for a callback. :) 👍

**Pull request merged**
