### PR TITLE
Fetch interceptor: Remove code duplication

### PR DESCRIPTION
**Pull request by AdamWillden**
Ran the tests and they pass so don't think I've broken anything!

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@AdamWillden Looks good. The tests might pass because not everything has been covered yet. Would you mind adding tests for this?

**Comment by AdamWillden** [comment]
I'll try and get to it this week @RWOverdijk

**Comment by AdamWillden** [comment]
@RWOverdijk 

I'll probably end up closing this pull request and opening another that complies to `CONTRIBUTING.md`

However I might need a hand understanding how you want the test to be written. The way the tests are done using the dependency injection container is different to how I usually do my tests. 

I usually mock the dependencies and create an instance which has the state of the dependencies set via mocks I.E. auth.isAuthenticated() will return true for some tests and false for others, same with config.current.httpInterceptor. The contents of a test may look something like this:

``` js
let authenticationMock = {
  isAuthenticated: () => { return true; }
  getToken: () => { return 'someToken'; };
};
let configMock = {
  current: {
    httpInterceptor: true,
    authHeader: 'AuthoriseHeader'
    authToken: 'AuthoriseToken'
  }
}

let fetchClient = new FetchClient(null, null, authenticationMock, configMock)

let interceptor = fetchClient.interceptor();
let request = ..something...;

interceptor.request(request);

expect(request.headers.append).toHaveBeenCalledWith('AuthoriseHeader', 'AuthoriseToken someToken')
```

If I do something like the above then I can continue but if I need to use the container I will need some help to understand how it might look.

**Comment by RWOverdijk** [comment]
@AdamWillden It doesn't really matter to be honest. I use a real container, to cause real scenarios. I want unexpected behavior in my tests while writing them, as to cover more ground (as long as I eventually know exactly what's going on :)). If I mock, I might not catch errors that only occur when combining certain pieces of functionality.

That being said, it doesn't matter how you write the tests imo. :)

**Comment by AdamWillden** [comment]
@RWOverdijk okay. I'll continue down my route, some tests are better than none!

i'm just not sure how I'd use the container style to verify that the request contains the headers as expected (or not as the case may be).

**Comment by RWOverdijk** [comment]
@AdamWillden Set up a test server :) https://github.com/SpoonX/aurelia-orm/blob/master/build/tasks/test.js#L9

**Pull request closed without merging**
