### PR TITLE
Hotfix oauth defaults

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Another excellent PR... You're on fire. I almost feel bad about asking this, but could you add tests to prove this works?

**Comment by doktordirk** [comment]
tricky. becomes apparent when first linking google and then facebook. 
google options added 'scopePrefix' to the default which carried over to facebook lets it fail. 
but i'll try to think of something

**Comment by doktordirk** [comment]
there is no authorize test of sorts yet as i see it. i guess it'll need a dummy provider to test authorization. that's slightly over my head. while eager to learn, i think i'll have to leave that to you (unless you give my very good starting instructions)

**Comment by doktordirk** [comment]
maybe we can copy some from https://github.com/sahat/satellizer/tree/master/test

**Comment by RWOverdijk** [comment]
That might be a good idea. We can also set up a test server in the test setup ([like I did with ORM](https://github.com/SpoonX/aurelia-orm/blob/master/build/tasks/test.js#L9)).

**Comment by doktordirk** [comment]
already had a look there. would be nice though if we could connect to facebook / google itself for realy proper testing. i googled for some public facebook account we could use, but seems there isn't any. maybe set up facebook/google accounts for testing?

**Comment by doktordirk** [comment]
a spoonx test app or so?

**Comment by doktordirk** [comment]
fyi: didn't have much time, but i'm still on adding tests

**Comment by RWOverdijk** [comment]
No worries. I appreciate all your help.

**Pull request merged**
