### PR TITLE
fixed setMe+  added missing dev dependency

### PR DESCRIPTION
**Pull request by doktordirk**
must have had my code mixed when i've aded setMe the way it was :(

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk This will cause very harmful side effects.

You're not passing in any criteria, which will cause most restful api's to update _all_ records. So unless you want all users to have the same profile info, I suggest we add some criteria to the update. Usually this would be something like `/user/:id` or `/user?id=:id`.

**Comment by doktordirk** [comment]
hmm, while i see that skiping creteria like this wasn't clever, i don't get your suggestion. setMe uses the profile path eg "users/me" thus can't overwrite other profiles.
as for overwiting unsend own profile parts: it's using put, so shouldn't that only update what got send?

**Comment by doktordirk** [comment]
ps: using a rest service where one can overwrite someone elses profile, has other problems as well imho

**Comment by doktordirk** [comment]
so i was thinking of this. (i will need to test updating with criteria still)

**Comment by RWOverdijk** [comment]
@doktordirk That truly depends on your setup. Usually, in a restful API, you update specific resources (and don't let the server handle it). So sending a PUT to /me, could work.

I like this approach, looks good. Let me know when you're done testing :)

**Comment by doktordirk** [comment]
can't test now now fully. maybe quickfix and i'll improve it later

**Pull request merged**
