### PR TITLE
Fix client

### PR DESCRIPTION
**Pull request by doktordirk**
tricky now. last build is broken, but renaming got merged already!?

### CODE REVIEW

**Comment by AdamWillden** [comment]
Yeah, you mentioned before that we could do with a master and a develop branch. Then we can still push out current version hotfixes even if we're progressing with next version.

**Comment by AdamWillden** [comment]
Haha, this is going to cause me a few conflicts!

**Comment by doktordirk** [comment]
sorry. i'm open for more convenient version. however, my last try on this caused this issue now with 2 month delay

**Comment by AdamWillden** [comment]
Yeah no worries dude. I'd rather this is  fixed first and I rebase my breaking changes on top anyway :-) I knew it would probably happen.

**Comment by doktordirk** [comment]
simpler is https://github.com/SpoonX/aurelia-authentication/pull/100

**Pull request closed without merging**
