### PR TITLE
feat(authService): signal the token expires

### PR DESCRIPTION
**Pull request by doktordirk**
use BindingSignaler to signal when the token expires

preview

### CODE REVIEW

**Comment by RWOverdijk** [comment]
I like this... We could thing about the key a bit more but the concept is cool. How would I use this?

**Comment by doktordirk** [comment]
https://www.danyow.net/aurelia-binding-behaviors/

${postDateTime | timeAgo & signal:'my-signal'}

and hopefully like as custom updateTrigger
if.bind="myPara | signal:'token-expired'"
aka the bind will be checked when token-expired is signalled

**Comment by RWOverdijk** [comment]
Oooooh that's cool. :D

**Comment by doktordirk** [comment]
ps: i'm open to change to a better signal name :smile:

**Comment by RWOverdijk** [comment]
I think I can live with this for now.

**Pull request merged**
