### PR TITLE
handle logout also if server logoutUrl fails

### PR DESCRIPTION
**Pull request by k2s**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
I sort of meant with [our guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit) in mind. But I can do that for you if you want

**Comment by k2s** [comment]
I did my best, but eslint fails on my commit on code which is not my.

**Comment by RWOverdijk** [comment]
@k2s I don't know how you did that... It works for me: https://github.com/SpoonX/aurelia-authentication/pull/324

**Comment by RWOverdijk** [comment]
@k2s Mind if I merge mine instead? Or care to try again?

**Comment by k2s** [comment]
@RWOverdijk pls. merge it :-) thank you.

**Pull request closed without merging**
