### PR TITLE
chore(baseConfig): clearify baseUrl

### PR DESCRIPTION
**Pull request by doktordirk**
@AdamWillden please review

### CODE REVIEW

**Comment by RWOverdijk** [comment]
:+1: If this works the same

**Comment by AdamWillden** [comment]
Ahh you mentioned me to look at this, sorry I didn't notice till now.

It **looks** okay to me. Do you want me to implement the same changes in my local app? I'm not doing any oauth however.

**Comment by AdamWillden** [comment]
@doktordirk also did you mean 'clairfy' (not 'clearify')

**Comment by doktordirk** [comment]
@AdamWillden 1+2 = 2 +1 :smile: 
the code is unchanged.

**Comment by AdamWillden** [comment]
@doktordirk indeed that's the hope anyway. Just cant ignore the posibility that it may reveal a bug where 1 = 1 (missing + 2)

**Comment by doktordirk** [comment]
hehe true. but i think i check the code quite carefully for baseUrl appearances

**Comment by AdamWillden** [comment]
I did too. I think we'll be safe enough :-)

**Pull request merged**
