### PR TITLE
chore(project):  fix d.ts

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Review by srfabio — APPROVED** [review]
All fine.

**Review by TomFoyster — APPROVED** [review]

**Review by RWOverdijk — APPROVED** [review]

**Comment by ghost** [comment]
Can we get these changes pushed to NPM in a new minor version?

**Comment by doktordirk** [comment]
right, i forgot that npm-based installs use the package and not github.

**Comment by doktordirk** [comment]
@RWOverdijk since master has changed since, can you like

``` sh
git checkout --detach e083ecb -f
gulp prepare-release
npm publish
```

**Pull request merged**
