### PR TITLE
(bug) allow object passed as second arg to authService.login()

### PR DESCRIPTION
**Pull request by MartinMason**
modified the type of the second argument to allow string or object as the first argument to the login function does

### CODE REVIEW

**Review by doktordirk — APPROVED** [review]

**Comment by mchoy** [comment]
Can you please update the definition file for the login as well?  I have a typescript project, it's complaining about the second parameter can only be 'string or undefined'   Thanks.

**Comment by RWOverdijk** [comment]
@mchoy Feel free to submit a PR :) Otherwise open up a new issue and hope someone will take it on. We're currently swamped.

**Comment by MartinMason** [comment]
@mchoy You must be using jspm. In the [Aurelia-validation.d.ts file ](https://github.com/SpoonX/aurelia-authentication/blob/master/dist/aurelia-authentication.d.ts )in the repo, on line 573, you'll see the changes are reflected. When I installed the typedef file with typings, the changes aren't there.

**Comment by mchoy** [comment]
@MartinMason I think @RWOverdijk fixed it for the 3.2.0 release.  Thanks.

**Pull request merged**
