### PR TITLE
fix(Update aurelia-authentication.js): Changed to this.authentication.updateAuthenticated() to this.updateAuthenticated()

### LINKED ISSUE #370: Method 'updateAuthenticated' undefined
I'm getting errors "Object doesn't support property or method 'updateAuthenticated' thrown" when trying to execute the following lines in AuthService.js storageEventHandler method

```
    // in case auto refresh tokens are enabled
    if (this.config.autoUpdateToken && this.authentication.getAccessToken() && this.authentication.getRefreshToken()) {
      // we just need to check the status of the updated token we have in storage
      this.authentication.updateAuthenticated();
```

The problem is that there is no updateAuthenticated method defined in the Authentication class. Oddly enough, this has only manifested itself when executing in IE 11.

I'm using version 3.7.0

### PR DESCRIPTION
**Pull request by vincentw56**
fix(aurelia-authentication.js): Changed this.authentication.updateAuthenticated() to this.updateAuthenticated()

The method this.authentication.updateAuthenticated() is not found. Changed it to this.updateAuthenticated() which is the correct method

fixes #370

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@vincentw56 This is good 👌 

Could you update the commit message though? That helps with generating the CHANGELOG. https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit

**Comment by vincentw56** [comment]
I made the change. Let me know if it still doesn't look right.

**Comment by RWOverdijk** [comment]
The change doesn't seem to have been pushed. I'm sorry for the really late reply, also.

**Comment by vincentw56** [comment]
Not sure I understand what you mean. The change is there, I can see it in the file. What more do you need from me?

**Comment by RWOverdijk** [comment]
I'll perform the change later.

**Comment by RWOverdijk** [comment]
https://github.com/SpoonX/aurelia-authentication/pull/380

**Pull request closed without merging**
