### PR TITLE
feat(authService): add logout handling for openid connect

### PR DESCRIPTION
**Pull request by MartinMason**
OIDC providers like IdentityService and OpenIddict handle logout very similarly to authenticate. Feature adds logoutEndpoint to oAuth2 configuration and handles calling redirection to this endpoint very similarly to authenticate.

### CODE REVIEW

**Comment by doktordirk** [comment]
ui , quite some work. can you add to the readme.md an oidc support note, update doc/baseConfig.md and probably better add andoc/oidc.md page?

**Comment by MartinMason** [comment]
Sure will. I'm likely not going to get around to it until this weekend but you're okay with the approach? I tried to make it as unobtrusive as possible. 

Oh. BTW, the jspm config still references rc1 aurelia packages. I ran a jspm update on the project and all the unit tests still pass. but didn't want to include those changes with this commit.

**Comment by doktordirk** [comment]
yeah, looked all good to me. nicely done!

as for jspm. it's best to keep the dependencies as low as possible. if only rc1 is needed for it to work, then that it should be. else users can get unneeded forks more easily

**Comment by MartinMason** [comment]
Updated docs

**Comment by doktordirk** [comment]
- logout function in the docs needs an update
- the state function might be moved into static BaseConfig.getStateAlphaNum() or so
- i/one should make the onLogout call on a finally, as i think it also should be called for failed logouts
- similarly should failed logout throw, or better resolve with {success: false, error: 'State mismatch'} or so (since someone mentioned that promise rejection shouldn't be used for control flow)?

i'll merge anyways, as those are minor things and i believe good stuff shouldn't lay around too long

**Pull request merged**
