### PR TITLE
Feat timeout

### PR DESCRIPTION
**Pull request by doktordirk**

### CODE REVIEW

**Comment by doktordirk** [comment]
closes https://github.com/SpoonX/aurelia-authentication/issues/107
closes https://github.com/SpoonX/aurelia-authentication/issues/121

**Comment by RWOverdijk** [comment]
Sounds and looks good. The comments are on the other PR (this is based off of that)

**Comment by doktordirk** [comment]
i'm fine with leaving that to 3.1 . get it in now or wait?

**Comment by RWOverdijk** [comment]
Maybe for the best (getting it in sooner rather than later I mean)

**Pull request merged**
