### PR TITLE
chore(project): update dependencies

### PR DESCRIPTION
**Pull request by RWOverdijk**
@MaximBalaganskiy Because of an outdated dep that used event-stream ([yeah. Remember that?](https://github.com/dominictarr/event-stream/issues/116)) the dependencies had to be updated, otherwise the tests wouldn't run. I'm not sure how you got the tests to run to be honest.

In any case, could you take this out for a spin and let me know if it works for you?

It should, all dependencies are in a safe version range.

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
I killed the lock file and after `npm i` all tests worked

**Comment by MaximBalaganskiy** [comment]
also works in this branch

**Comment by RWOverdijk** [comment]
PErfect.

**Comment by RWOverdijk** [comment]
@MaximBalaganskiy v3.8.3

Enjoy 😄

**Comment by MaximBalaganskiy** [comment]
Thank! 👏

**Pull request merged**
