### PR TITLE
doc: Typos corrected in documentation

### PR DESCRIPTION
**Pull request by maadborn**
Added a missing comma to the Quick Start sample config.
Corrected a comment in the config stating the wrong method.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Nice catch. Could you perhaps rephrase the commit message according to the [commit guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)?

**Comment by RWOverdijk** [comment]
@maadborn Thank you for the pr! Would you be so kind as to change the commit messages to follow our [commit guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)? Otherwise I can easily do it for you :)

**Comment by maadborn** [comment]
Sorry, I'm not really sure what I am missing in the commit message. I tried to correct them by cloning a local branch and merging it back to the PR, but I guess it might have made it worse. :P If you're okey with it, please fix it and I'll learn from it till next time, thanks!

**Comment by RWOverdijk** [comment]
@maadborn No problem. The correct format would have been:

`doc(baseConfig): Add missing comma`

**Comment by RWOverdijk** [comment]
@bas080 Could you open up a PR for this with the correct commit messages, and ping @maadborn?

**Review by bas080 — APPROVED** [review]

**Comment by RWOverdijk** [comment]
@maadborn https://github.com/SpoonX/aurelia-authentication/pull/311

**Comment by maadborn** [comment]
Super, thanks!

**Pull request closed without merging**
