### PR TITLE
feat(authService): add default headers and clientSecret in config

### PR DESCRIPTION
**Pull request by groenlid**
Add some default headers to the baseConfig that will be appended when using .login() and .refreshToken(). This is to support IdentityServer 4 with the openId spec http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest.
Gives us the posibility to use application/x-www-form-urlencoded as content-type.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@groenlid Nice PR. One question before I do the whole review stuff, can't this be solved with interceptors / endpoint defaults instead? it feels like this solution is for a very specific case, and could just as well be configured on the endpoint through aurelia-api.

**Comment by groenlid** [comment]
Yeah, maybe it's easier to just add an interceptor to the httpClient.
```js
this.httpClient.configure(config =>
  config.withInterceptor({
	request(request){
	  if(request.url.indexOf(auth.baseUrl) !== -1)
		request.headers.set('Content-Type', 'application/x-www-form-urlencoded');
	  return request;
	}
  })
)
```

Any thoughts on the clientSecret part of the PR?

**Comment by RWOverdijk** [comment]
Hm.. Well, it would be nice if this module worked ootb with IdentityServer 4. It's difficult for me to review that part because I never used it before. I'd have to set it up, check it out etc.

I'll take a look at this a bit later. In the meantime, the code-style used doesn't match ours. Could you run `gulp lint`? It's mainly spacing for if: 

```js
if (condition) {
  // code
}
```

**Comment by groenlid** [comment]
Ok. We're using IS 4 with the resource owner flow.
The linting does not return any errors on my machine or on travis, but I'll change the syntax to match yours. 👍

**Comment by RWOverdijk** [comment]
@groenlid I'll test if this doesn't break any of the other known cases. If it doesn't, I'll merge this and publish :)

**Comment by RWOverdijk** [comment]
I keep forgetting about this PR, I'm really sorry.

**Review by RWOverdijk — APPROVED** [review]

**Comment by RWOverdijk** [comment]
@groenlid Published as 3.5.0

**Pull request merged**
