### PR TITLE
feat(authentication): Add option to always store all received properties

### PR DESCRIPTION
**Pull request by diegotroitino**
By [this issue](https://github.com/SpoonX/aurelia-authentication/issues/374) i've added an option to allow keep stored all old response properties. This allows to work with a single refresh_token that was received once and the expiration only is extend.

The new config option is the 'keepOldResponseProperties'

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@diegotroitino Hey! I'm not entirely sure what this does still, but I appreciate the PR nonetheless. Could you update the commit messages according to our [contributing guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)?

**Comment by diegotroitino** [comment]
What's the problem with the message "_refactor(authentication): apply coding rules_"?
I've tried many messages

Sorry, that's my first open source PR. 
;-)

**Comment by RWOverdijk** [comment]
It's not the refactor message, it's doc which should be docs.

**Review by doktordirk — APPROVED** [review]
looks good

**Pull request merged**
