### PR TITLE
feat(project): name auth appropriatly and refactor

### PR DESCRIPTION
**Pull request by doktordirk**
BREAKING CHANGE: AuthService instance renamed to authService and Authentication instance renamed to authentication

### CODE REVIEW

**Comment by RWOverdijk** [comment]
That's worth a big :+1:

Consistency :)

**Comment by AdamWillden** [comment]
I've looked this over a few times and not that it matters (more for my curiosity) what exactly makes this a breaking change? An answer to that will probably answer this: @doktordirk, you mentioned to me that this PR needed discussion, what needs discussing?

**Comment by doktordirk** [comment]
Those names are accessable and used by our customers

On Sat, Apr 2, 2016 at 10:26 AM -0700, "Adam Willden" notifications@github.com wrote:

I've looked this over a few times and not that it matters (more for my curiosity) what exactly makes this a breaking change? An answer to that will probably answer this: @doktordirk, you mentioned to me that this PR needed discussion, what needs discussing?

---

**Comment by AdamWillden** [comment]
Ah yes okay, that makes sense!

**Comment by doktordirk** [comment]
@RWOverdijk this one, unless @AdamWillden want's to change my parts anyways

**Comment by AdamWillden** [comment]
:+1: I'm good with this!

**Comment by RWOverdijk** [comment]
:+1:

**Pull request merged**
