### PR TITLE
fix(authService): storageChangedReload  optional (default: false)

### PR DESCRIPTION
**Pull request by doktordirk**
ref https://github.com/SpoonX/aurelia-authentication/issues/278

i'm not sure about the default false there. i'd prefer true since that prevents sensitive data still being displayed

@RWOverdijk thoughts?

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk False for BC.

**Comment by doktordirk** [comment]
@RWOverdijk  i disagree that BC rules it all. but well, mind approving then

**Review by RWOverdijk — APPROVED** [review]

**Comment by doktordirk** [comment]
@RWOverdijk rechecked and totally BC to 3.0.0
but you might wanna quickly check my small doc changes. since i wasn't allowed to use true as default, i added the recommendation to set it to true

**Comment by doktordirk** [comment]
@nexbit do you agree with recommending to users to set it to true themselves?

**Comment by RWOverdijk** [comment]
@doktordirk You may add the default as true, but then the bump will be minor in stead of patch.

**Comment by pfurini** [comment]
> rechecked and totally BC to 3.0.0

The commit that added forced reload is after 3.0 release, and that reload breaks when you want to authenticate in popup mode (checked on my code base).
So I really think that was a BC break..

> do you agree with recommending to users to set it to true themselves?

If they know the implications, either default is fine to me. Regarding the BC principle, only a default of `false` should be acceptable, even for a minor ver bump.. If someone has a "no redirect at all" approach in place, that reload alone would break their app.

**Pull request merged**
