### PR TITLE
Updated build d.ts file generation to exclude imports and prevent exporting 'authUtils.js'.

### PR DESCRIPTION
**Pull request by kellyethridge**
This update will exclude all imports in the d.ts file generation. It will also prevent the generation of export {authUtils} which TS doesn't seem to like having.

### CODE REVIEW

**Comment by kellyethridge** [comment]
This pull-request probably shouldn't be accepted until after the removal of the spoonx prefix is applied.

**Comment by doktordirk** [comment]
export utils in es6 and not in ts isn't nice. 
@RWOverdijk you really need  authUtils?

**Comment by doktordirk** [comment]
i'll fixed the authUtils issue https://github.com/SpoonX/aurelia-authentication/pull/69
so ll need to reup after it's merged

**Comment by RWOverdijk** [comment]
@doktordirk _I_ don't need them. They were there. I think we could stick them in a class of static methods and be done with that.

**Comment by doktordirk** [comment]
Its a philosophical question: We export them, they should be documented and maintained. I don't see authUtils as part of the authentication package

**Comment by RWOverdijk** [comment]
@doktordirk Perhaps. But what's the evil in exposing them?

**Comment by doktordirk** [comment]
'evil' isn't a valid concept in philosophy :smile: 
well, its'y our name on it hehe and since the d.ts export issue is solved with the static class methods it's not causing issues to export it

**Comment by RWOverdijk** [comment]
If we're going to nitpick, philosophy doesn't belong in the world of programming as philosophy doesn't know any answers, only questions and proposals. Debates are useful though haha.

At some point you have to make a decision. :) If we take it out like this it's fine as well. I don't mind either way. As long as the actual fundamentals work, which they do. :)

**Comment by doktordirk** [comment]
i'll look over it's features again, else i'll ask Adam to split the tie

**Comment by doktordirk** [comment]
@kellyethridge can you rebase? in case you need tips, just ask. in case you need a merge tool, kdiff3 does a good job. might look tricky at first, but one gets used to it and it's invaluable for this kind of job.

ps: rebuild not needed. we'll need to do one anyways when releasing

**Comment by doktordirk** [comment]
this one needs rebasing. says 'This branch has conflicts that must be resolved" meaning the repos has changed meanwhile and your PR can't be automatically applied anymore. rebasing means that you move the branching point of your PR up and apply your changes on that new branching point. when doing that, there will be conflicts which'll need resolving. i use kdiff3 for that. it's slightly overwelming at first, but the best there is, afterwards, just force push your changes with git push -f origin HEAD

(ps in this case you also could choose the easy way. just make a new PR from our current repo and copy the thew build task over)

**Comment by kellyethridge** [comment]
Submitted a new PR.

**Comment by doktordirk** [comment]
replaced with https://github.com/SpoonX/aurelia-authentication/pull/82

**Pull request closed without merging**
