### PR TITLE
Typings@package.json and Better WebPack support 

### PR DESCRIPTION
**Pull request by icanhasjonas**
- Added `typings` field in `package.json`
- Declared aurelia build resources in `package.json`

### CODE REVIEW

**Comment by doktordirk** [comment]
tx. it's part of https://github.com/SpoonX/aurelia-authentication/pull/204 and released shortly

**Comment by doktordirk** [comment]
see https://github.com/SpoonX/aurelia-authentication/pull/204

**Comment by icanhasjonas** [comment]
@doktordirk nice! don't forget the `package.json` update as it streamlines webpack usage

**Comment by doktordirk** [comment]
@icanhasjonas darn! that got lost while rebasing somehow. tx, good catch!

**Pull request closed without merging**
