### PR TITLE
README.md: Added missing comma

### PR DESCRIPTION
**Pull request by perlun**
Visual Studio Code told me about it. :)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@perlun Awesome!

I know it's a silly request, especially because it's only one comma, but could you change the commit message to adhere to [our contributing guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)?

Something like `doc(readme): add missing comma`

It's not a must, I can do it myself, but it would be nice.

**Comment by perlun** [comment]
> I know it's a silly request, especially because it's only one comma, but could you change the commit message to adhere to our contributing guidelines?

Sure, I want to be nice and play by the rules (wasn't aware of them in this case). There we go, commit amended.

----

As for generating changelogs via git commit messages, I find that a great thing, both:

- that you generate changelogs 😉, and
- that you use the `git` commit messages to do it.

I do the same, all the time. I have even written a little tool that helps me do it (relying on the fact that my git tags are properly SemVer-named etc): https://github.com/perlun/changelog-rs

That tool which is useful to me, is based on a somewhat different presumption though: I don't force myself or my peers to use a particular formatting of the git commit messages, but instead I force myself and others 😉 to use the "squash all branches on merge" workflow. That way, I can just take the results of `git log rev1..rev2` and generate the changelog based on it. When using it on GitHub, I will even get cross-references to the proper PRs etc, automagically. There is (almost) always a 100% correlation between a singular commit and a single PR. (I say almost because it's still possible to make certain changes straight on the master branch etc.)

This, to me, seems like a simpler approach than enforcing a particular git commit message scheme. But it of course means that a large version bump (say, v1.1.0 to v1.2.0) with 50 different PRs will get a changelog that's very unmaintainable to read: it will just be a long list, with no differentiation between features, bug fixes, etc.

As of yet, this hasn't been a _huge_ problem for me since the software I maintain (at work and privately) is typically released on a much much more fine-granular basis, and I've yet been too lazy to try and enforce this commit message approach. 😄 I do find it a bit ugly as well, even though I clearly see the practical benefit of it. It's like trying to encode 3 different database fields into a single one, simply because there is no better way. It would be nicer if git allowed you to add "tags" to the commit in some way instead.

But anyway, I have 100% respect for people who might have a completely different opinion here.

**Comment by RWOverdijk** [comment]
I've done that before, but I like the format where I can step through the process (multiple commits) myself. In any case the changes are optional, and those who don't want to, don't have to. Any contributing developer is welcome, even if it means I have to reformat the commits myself :)

Thank you for your explanation though, it was very informative!

**Review by RWOverdijk — APPROVED** [review]

**Comment by perlun** [comment]
> I've done that before, but I like the format where I can step through the process (multiple commits) myself

Yeah, some people prefer to retain the multiple commits (either via merge commits or via "rebase all commits"). That's fine. I personally like the "birds-eye-view" that you get with the squash flow; all the details are available on GitHub _if_ i need them. But I'm not forced to see it when all I'm looking for is the overview, which I like.

> In any case the changes are optional, and those who don't want to, don't have to. Any contributing developer is welcome, even if it means I have to reformat the commits myself :)

That's really a good (but unfortunately a bit unusal!) attitude towards your peers. 👍 

Anyway, I like the idea of being able to "tag" a commit with metadata. I guess [git notes](https://www.kernel.org/pub/software/scm/git/docs/git-notes.html) could be use, but the conventional-changelog approach is arguably simpler because _everyone_ has easy access to the git commit messages.

**Pull request merged**
